name: smart_guide_to_medication
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  firebase_auth: ^5.5.1
  conditional_builder_null_safety: ^0.0.6
  cloud_firestore: ^5.6.5
  permission_handler: ^11.4.0
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Anek-Regular
      fonts:
        - asset: assets/fonts/AnekLatin-Regular.ttf
    - family: Anek-Medium
      fonts:
        - asset: assets/fonts/AnekLatin-Medium.ttf
    - family: Anek-SemiBold
      fonts:
        - asset: assets/fonts/AnekLatin-SemiBold.ttf
    - family: osamh

      fonts:
        - asset: assets/fonts/Alexandria-Medium.ttf
        - asset: assets/fonts/Alexandria-SemiBold.ttf
          style: italic
    - family: osamh_light
      fonts:
        - asset: assets/fonts/Alexandria-Light.ttf
        - asset: assets/fonts/Alexandria-Light.ttf
          style: italic
